server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.74.139:3306/cloud-order # ?serverTimezone=UTC?useSSL=false
    username: zmz
    password: Root_1234
  # 2.服务注册
  # 2.1 user微服务的名字
  application:
    name: orderservice
  # 使用并配置nacos注册中心
  cloud:
    nacos:
      server-addr: localhost:8848


# 配置本微服务 请求访问 userservice 微服务 的负载均衡规则
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载nacos注册中心下的，优先访问同集群下的微服务 的均衡规则
    # 但默认情况下NacosRule是同集群内随机挑选，不会考虑机器的性能问题。因此，Nacos提供了权重配置来控制访问频率，权重越大则访问频率越高。
ribbon:
  eager-load:
    enabled: true # 开启饥饿加载
    clients: # 指定饥饿加载的服务名称
      - userservice

# feign配置
feign:
  client:
    config:
      default:
        loggerLevel: BASIC
  httpclient:
    enabled: true  # 开启feign对HttpClient的支持
    max-connections: 200  # 最大的连接数
    max-connections-per-route: 50  # 每个路径的最大连接数

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
