server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes: # 网关路由配置
        - id: order_service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
        - id: user_service # 路由id，自定义，只要唯一即可
          # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://userservice # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言工厂，也就是判断请求是否符合路由规则的条件
            - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:  # 当前微服务中的路由过滤器
            - AddRequestHeader=key1, hello world! # 给请求头添加一个键值对

      default-filters:  # 全局路由过滤器
        - AddResponseHeader=key2, hello world!
      globalcors:
        add-to-simple-url-handler-mapping: true  # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8080"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*"  # 允许在请求中携带的头信息
            allowCredentials: true  # 是否允许携带cookie
            maxAge: 360000  # 这次跨域检测的有效期



logging:
  level:
    cn.itcast.gateway: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
