server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.101.74.139:3306/cloud-user # ?serverTimezone=UTC?useSSL=false
    username: zmz
    password: Root_1234
  # 2.服务注册
  # 2.1 user微服务的名字
#  application:
#    name: userservice
  # 使用并配置nacos注册中心
#  cloud:
#    nacos:
#      server-addr: localhost:8848
#      discovery:
#        ephemeral: false # 设置为非临时实例

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
#    pattern:
#      dateformat: MM-dd HH:mm:ss:SSS

